# -*- coding: utf-8 -*-
"""SpotfiyDownload.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8z3riozdGuYHjX1GKU1HpCNl97Mswk5
"""

!pip install spotipy

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import requests
def get_spotify_preview(song_name):
    sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id='52fa5150f66e4837875f44da7d66a987',
                                                                client_secret='8e5fe0183bcf458b8459a9d425ea8df7'))

    result = sp.search(q=song_name, type='track', limit=1)
    track = result['tracks']['items'][0]
    preview_url = track['preview_url']

    if preview_url:
        print(f"Preview URL: {preview_url}")
        response = requests.get(preview_url)
        if response.status_code == 200:
            with open(f"{song_name}.mp3", "wb") as file:
                file.write(response.content)
            print(f"Downloaded preview for '{song_name}' as {song_name}.mp3")
        else:
            print(f"Failed to download audio: {response.status_code}")
    else:
        print("No preview available for this song")

get_spotify_preview("I want it that way")